version: '3.9'

services:
  nginx:
    image: duteplyakov/nginx:v2
    ports:
      - 8080:80
    volumes:
      - php:/php
    networks:
      - les14
  php:
    image: duteplyakov/php-fpm:v1
    volumes:
      - php:/php    
    networks:
      - les14

volumes:
  php:

networks:
  les14:
